arb-dir: ./assets/l10n
template-arb-file: app_en.arb
output-dir: ./lib/src/l10n/generated/
output-localization-file: app_localizations.dart
untranslated-messages-file: ./assets/l10n/untranslated-messages-file.json
output-class: AppLocalizations
preferred-supported-locales: [en, vi]
use-deferred-loading: false
gen-inputs-and-outputs-list: true
synthetic-package: false
nullable-getter: false
format: true